# Generated by Django 4.0.6 on 2022-07-19 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cep', models.CharField(max_length=8)),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
